# Generated by Django 2.0.2 on 2018-02-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFieldVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
            ],
            options={
                'verbose_name': 'Date Field',
                'verbose_name_plural': 'Date Fields',
                'db_table': 'date_field_val',
            },
        ),
        migrations.CreateModel(
            name='EnumFieldVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('A', 'choice_A'), ('B', 'choice_B')], max_length=200)),
            ],
            options={
                'verbose_name': 'Enum Field',
                'verbose_name_plural': 'Enum Fields',
                'db_table': 'enum_field_val',
            },
        ),
        migrations.CreateModel(
            name='NumberFieldVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Number Field',
                'verbose_name_plural': 'Number Fields',
                'db_table': 'number_field_value',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'db_table': 'risk',
            },
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Risk Field',
                'verbose_name_plural': 'Risk Fields',
                'db_table': 'risk_field',
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='Risks.Risk')),
            ],
            options={
                'verbose_name': 'Risk Type',
                'verbose_name_plural': 'Risk Types',
                'db_table': 'risk_type',
            },
        ),
        migrations.CreateModel(
            name='TextFieldVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.RiskField')),
            ],
            options={
                'verbose_name': 'Text Field',
                'verbose_name_plural': 'Text Fields',
                'db_table': 'text_field_value',
            },
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.RiskType'),
        ),
        migrations.AddField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.RiskField'),
        ),
        migrations.AddField(
            model_name='enumfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.RiskField'),
        ),
        migrations.AddField(
            model_name='datefieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.RiskField'),
        ),
    ]
