# Generated by Django 2.0.2 on 2018-02-09 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='risk',
        ),
        migrations.AddField(
            model_name='risktype',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Risks.Risk'),
        ),
    ]
