# Generated by Django 2.0.2 on 2018-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
