# Generated by Django 2.0.2 on 2018-02-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0002_auto_20180210_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_field', to='Risks.RiskType'),
        ),
    ]
