# Generated by Django 2.0.2 on 2018-02-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0002_risk_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risks.Risk')),
            ],
        ),
    ]
