# Generated by Django 2.0.2 on 2018-02-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0002_auto_20180209_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='risk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Risks.Risk'),
        ),
    ]
