# Generated by Django 2.0.2 on 2018-02-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0003_auto_20180210_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='enumfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_filed', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='textfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_filed', to='Risks.RiskField'),
        ),
    ]
