# Generated by Django 2.0.2 on 2018-02-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0003_auto_20180209_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefieldval',
            name='risk_field',
        ),
        migrations.RemoveField(
            model_name='datefieldval',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='enumfieldval',
            name='risk_field',
        ),
        migrations.RemoveField(
            model_name='enumfieldval',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='textfieldval',
            name='risk_field',
        ),
        migrations.RemoveField(
            model_name='textfieldval',
            name='risk_type',
        ),
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_type', to='Risks.RiskType'),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='risk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_type', to='Risks.Risk'),
        ),
    ]
