# Generated by Django 2.0.2 on 2018-02-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0003_risktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDateVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldEnumVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('A', 'choice_A'), ('B', 'choice_B')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldNumberVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldTextVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('risk_type', models.ManyToManyField(to='Risks.RiskType')),
            ],
        ),
        migrations.AddField(
            model_name='fieldtextval',
            name='risk_field',
            field=models.ManyToManyField(to='Risks.RiskField'),
        ),
        migrations.AddField(
            model_name='fieldnumberval',
            name='risk_field',
            field=models.ManyToManyField(to='Risks.RiskField'),
        ),
        migrations.AddField(
            model_name='fieldenumval',
            name='risk_field',
            field=models.ManyToManyField(to='Risks.RiskField'),
        ),
        migrations.AddField(
            model_name='fielddateval',
            name='risk_field',
            field=models.ManyToManyField(to='Risks.RiskField'),
        ),
    ]
