# Generated by Django 2.0.2 on 2018-02-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0004_auto_20180210_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='textfieldval',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='Risks.RiskField'),
        ),
    ]
