# Generated by Django 2.0.2 on 2018-02-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0005_auto_20180209_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_val', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_val', to='Risks.RiskType'),
        ),
    ]
