# Generated by Django 2.0.2 on 2018-02-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risks', '0007_auto_20180211_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefieldval',
            name='risk_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='enumfieldval',
            name='risk_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enum_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='numberfieldval',
            name='risk_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_field', to='Risks.RiskField'),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_field', to='Risks.RiskType'),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_type', to='Risks.Risk'),
        ),
        migrations.AlterField(
            model_name='textfieldval',
            name='risk_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='Risks.RiskField'),
        ),
    ]
